version: "3.7"

services:

  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    image: allir/jenkins:latest
    container_name: jenkins_master
    ports:
      - '8080:8080'
    networks:
      - jenkins_network
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    restart: on-failure

networks:
  jenkins_network:
